dafiti_web:
    resource: "@DafitiWebBundle/Controller/"
    type:     annotation
    prefix:   /

dafiti_admin:
    resource: "@DafitiAdminBundle/Controller/"
    type:     annotation
    prefix:   /

